{"name": "test_connection", "status": "broken", "statusDetails": {"message": "AttributeError: 'Engine' object has no attribute 'table_names'", "trace": "def test_connection():\n        db = create_engine(db_connection_string)\n>       names = db.table_names()\nE       AttributeError: 'Engine' object has no attribute 'table_names'\n\nмое\\test_database.py:10: AttributeError"}, "start": 1740647412222, "stop": 1740647412222, "uuid": "c535d574-a62d-4b34-ad76-f22d1278d9e4", "historyId": "c2c57bf24538a3038d13f99651b219c8", "testCaseId": "c2c57bf24538a3038d13f99651b219c8", "fullName": "мое.test_database#test_connection", "labels": [{"name": "parentSuite", "value": "мое"}, {"name": "suite", "value": "test_database"}, {"name": "host", "value": "LAPTOP-LD04488S"}, {"name": "thread", "value": "20544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "мое.test_database"}]}